name: flutter_mini_app_bridge
description: "A Bridge to communicate between Flutter and Web Based Mini App"
version: 1.0.0+1
repository: https://github.com/AgmoStudioSdnBhd/flutterpack
issue_tracker: https://github.com/AgmoStudioSdnBhd/flutterpack/issues?q=is%3Aissue+is%3Aopen
homepage: https://www.agmostudio.com/

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
