name: multimedia_gallery
description: "A multimedia gallery for Flutter. This gallery support image panning and zooming, video viewing and audio playing with multiple media format."
version: 0.0.1+7
# Uncomment to enable the github link once go live.
# repository: https://github.com/AgmoStudioSdnBhd/flutterpack
# issue_tracker: https://github.com/AgmoStudioSdnBhd/flutterpack/issues?q=is%3Aissue+is%3Aopen+
homepage: https://www.agmostudio.com/
environment:
  sdk: '>=3.2.4 <4.0.0'
  flutter: ">=1.17.0"

platforms:
  android:
  ios:

dependencies:
  flutter:
    sdk: flutter
  video_player: ^2.8.2
  audioplayers: ^5.2.1
  palette_generator: ^0.3.3+3
  intl: ^0.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
flutter:
  assets:
    - assets/