name: multimedia_gallery
description: "A multimedia gallery for Flutter. This gallery support image panning and zooming, video viewing and audio playing with multiple media format."
version: 0.0.6+20
repository: https://github.com/AgmoStudioSdnBhd/flutterpack
issue_tracker: https://github.com/AgmoStudioSdnBhd/flutterpack/issues?q=is%3Aissue+is%3Aopen+
homepage: https://www.agmostudio.com/
environment:
  sdk: '>=3.2.4 <4.0.0'
  flutter: ">=1.17.0"

platforms:
  android:
  ios:

dependencies:
  flutter:
    sdk: flutter
  video_player: ^2.8.2
  audioplayers: ^6.0.0
  palette_generator: ^0.3.3+3
  intl: ^0.19.0
  provider: ^6.0.3
  skeletons: ^0.0.3
  loading_indicator: ^3.1.1
  video_thumbnail: ^0.5.3
  skeletonizer: ^1.3.0
  image_gallery_saver_plus: ^3.0.5
  url_launcher: ^6.3.0
  android_intent_plus: ^5.0.2
  http: ^1.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
flutter:
  assets:
    - assets/