name: multimedia_gallery
description: "A image viewer gallery that display image, video and audio."
version: 0.0.1+4
environment:
  sdk: '>=3.2.4 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  video_player: ^2.8.2
  audioplayers: ^5.2.1
  palette_generator: ^0.3.3+3
  intl: ^0.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
flutter:
  assets:
    - assets/